name: NodeBase

on:
  workflow_dispatch:
    inputs:
      node_version:
        description: "Node Version Name"
        default: 10-alpine
        required: true
      tag:
        description: "Tag Name"
        default: 10
        required: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: images/basenode
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: NODE_VERSION=${{ github.event.inputs.node_version }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/basenode:${{ github.event.inputs.tag }}
            ghcr.io/${{ github.repository_owner }}/basenode:${{ github.event.inputs.tag }}
