name: php-full

on:
  workflow_dispatch:
    inputs:
      phpversion:
        description: "PHP Version"
        default: 7.4
        required: true
      with-loaders:
        description: "Enter '-loaders' to build with PHP loaders"
        required: false
jobs:
  php-warden:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: images/php-fpm/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            PHP_TAG=${{ github.event.inputs.phpversion }}
            WITH_LOADERS=${{ github.event.inputs.with-loaders }}
          tags: |
           ${{ secrets.DOCKERHUB_USERNAME }}/warden-php:${{ github.event.inputs.phpversion }}
            ghcr.io/${{ github.repository_owner }}/warden-php:${{ github.event.inputs.phpversion }}
  php-m2:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: images/php-fpm/magento2
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: PHP_TAG=${{ github.event.inputs.phpversion }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/warden-php-m2:${{ github.event.inputs.phpversion }}
            ghcr.io/${{ github.repository_owner }}/warden-php-m2:${{ github.event.inputs.phpversion }}
  php-m2-debug:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: images/php-fpm/magento2/xdebug3/Dockerfile
          context: images/php-fpm/context
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: PHP_TAG=${{ github.event.inputs.phpversion }}
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/warden-php-m2-xdebug3:${{ github.event.inputs.phpversion }}
            ghcr.io/${{ github.repository_owner }}/warden-php-m2-xdebug3:${{ github.event.inputs.phpversion }}